
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka01
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka01
  template:
    metadata:
      labels:
        app: eureka01
    spec:
      nodeName: yun1
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - name: eureka01
        image: yun.rep:5000/svc-center
        command: ["java"]
        args: ["-jar", "/eureka.jar","--spring.profiles.active=docker","--server.port=8001","--eureka.instance.hostname=yun1","--eureka01.host=yun1","--eureka01.port=8001","--eureka02.host=yun2","--eureka02.port=8002","--eureka03.host=yun3","--eureka03.port=8003"]
        ports:
        - name: http
          containerPort: 8001
          hostPort: 8001
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      imagePullSecrets:
        - name: yun-reg
---

apiVersion: v1
kind: Service
metadata:
  name: eureka01
  namespace: store
  labels:
    app: eureka01
spec:
  ports:
  - port: 8001
    name: eureka01
    targetPort: 8001
  selector:
    app: eureka01