
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: store-order
  namespace: store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-order
  template:
    metadata:
      labels:
        app: store-order
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - name: store-order
        image: yun.rep:5000/store-order
        command: ["java"]
        args: ["-jar", "/store-order.jar","--spring.profiles.active=docker","--eureka01.host=yun1","--eureka01.port=8001","--eureka02.host=yun2","--eureka02.port=8002","--eureka03.host=yun3","--eureka03.port=8003"]
        ports:
        - name: http
          containerPort: 8763
          hostPort: 8763
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8763
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8763
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      imagePullSecrets:
        - name: yun.rep.password
